### ISSUE TITLE
archiso hakkında

### ISSUE THREAD

**Issue by sulincix** [NERV-IT/nerv-linux#1]
Archiso yerine teaiso kullanabilirsiniz. Ayarlaması daha basit ve daha az sorun çıkartıyor. 

https://gitlab.com/tearch-linux/applications-and-tools/teaiso

https://aur.archlinux.org/packages/teaiso

**Comment by sulincix** [comment]
archiso profillerii teaiso içine aktarabiliyorsunuz.

**Comment by kunamech** [comment]
Tavsiyen için teşekkürler. Akşam build scriptini yeniden yazarken teaiso için de bir argüman ekleyeceğim.

**Comment by kunamech** [comment]
Bu arada AUR paketi build'in 4. ya da 5. aşamasında başarısız oluyor. Elle kurdum ama ona el atmak isteyebilirsiniz. Yeniden denediğimde detaylı bir bilgi veririm.
